sudo: required
services:
    - docker

before_install:
    - docker build -t kissta/docker-react-simplev2 -f Dockerfile.dev .

script:
    - docker run -e CI=true kissta/docker-react-simplev2 npm run test