sudo: required
services:
    - docker

before_install:
    - docker build -t kissta/docker-react-simplev2 -f Dockerfile.dev .

script:
    - docker run -e CI=true kissta/docker-react-simplev2 npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-us-east-2-233080411415"
    bucket_path: "docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY